server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway: #网关设置
      discovery:
        locator: #开启从注册中心动态路径,并实现负载均衡,默认是false
          enabled: true
      routes:
        - id: paymentLb_route
          uri: lb://PAYMENT  #从注册中心去找服务,lb是实现负载均衡
          predicates:
            - Path=/payment/lb
        - id: paymentGet_route #路由id,要求唯一
          uri: http://localhost:8001 #匹配后提供给服务的路由地址
          predicates:
            #断言,路径匹配后继续进行匹配
            - Path=/payment/get/**
        - id: blog_rout
          uri: http://randycout.com
          predicates: #randycout.com/types/-1
            - Path=/types/** #localhost:9527/types/-1
eureka:
  instance:
    hostname: gateway9527
    instance-id: gateway9527
    prefer-ip-address: true
  client:

    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/