server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7005.com:7005/eureka/ #集群版
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  #单机版