server:
  port: 82
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true #检索服务
    register-with-eureka:  true #注册到注册中心
  instance:
    instance-id: order82
    prefer-ip-address: true
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接使用的时间，适用于网络状况正常的情况下，两端连接所用的时间(默认这个时间是1s)
  ConnectionTimeout: 5000
spring:
  application:
    name: order

